### ISSUE TITLE
Run it from docker-compose

### ISSUE THREAD

**Issue by Vligsu** [Celedhrim/docker-kodi-server#27]
Hello celedhrim,
hello everyone!

I'm trying to get it running with docker-compose via Portainer, but with no success so far. Though no error messages in logs, the UPnP device does not show up. Loos like container does not check the "/path/to/kodi-server-profile".

Docker-compose yaml:
```
version: "2.1"
services:
  kodi-server:
    image: celedhrim/kodi-server
    container_name: kodi-server
    environment:
      - TZ=Europe/Berlin
      - PUID=1024
      - PGID=101
    volumes:
      - /volume1/kodi:/usr/share/kodi/portable_data celedhrim/kodi-server
    ports:
      - 8089:8089  # web access
    restart: unless-stopped
```

Container logs:
```
W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
```

What do I miss? Any help appreciated :)
